### ISSUE TITLE
Not a valid Win32 application.

### ISSUE THREAD

**Issue by seriosbrad** [ultrasn0w/foo_drpc#2]
When installing "foo_drpc.dll" into /components with "discord-rpc.dll" and "send-presence.exe" into /foobar2000, foobar2000 tells me:

```
Failed to load DLL: foo_drpc.dll
Reason: Not a valid Win32 application.
```

foobar2000 v1.3.16

**Update:**
I had to use the win32-dynamic\bin even though I'm on a 64 bit install.  Working well now!

**Comment by ultrasn0w** [comment]
Hi, 
First of all you don't need "send-presence.exe", its just an example program from the Discord dev team.
And yes indeed, you need the 32bit libraries because foobar2000 is a 32bit program itself and can't load 64bit libraries.
But thanks for reporting, I'll definitely should clarify that in the README.

I assume this issue is closed now.
