### ISSUE TITLE
Delay/Wrong song name when manually selecting tracks?

### ISSUE THREAD

**Issue by thxne** [ultrasn0w/foo_drpc#3]
Neat plugin, I'm really digging it. Just a couple small things I notice is there seems to be a delay sometimes from when Discord shows it from paused and listening status on a track. Also, whenever I am playing a song and manually select another song, or skip a couple tracks, it will sorta get stuck on a previous track that isn't the current one until I go in and fiddle with it by stopping the song, and replaying it.

**Comment by ultrasn0w** [comment]
yo,
Thanks for the feedback, hope you enjoying it :)

Yes, the Discord API for Rich Presence isn't something thats made for realtime changes, mabe you also noticed that when looking at the "official" Spotify integration.

Codewise, I send **every** song change, even if a track has info that dynamically changes during playback (At least since the latest version). Nothing more I could really do besides of sending it multiple times.
Sometimes it just needs almost 20 seconds or more to recognize that a new Rich Presence message has been sent.
That the previous message will be immediately displayed when a new one is sent out, is some really strange behaviour which I believe happens on Discords end.
Also mind the built in 0.42 second spam protection. Faster changes/skips will be not be send.

If there's still somthing you kind of want to have/think will be a good change, just let me know ;)

**Comment by ultrasn0w** [comment]
Closed by #13
